### ISSUE TITLE
Add possibility to close pressing enter key + aria-label

### ISSUE THREAD

**Issue by vincentaudebert** [springload/react-accessible-modal#2]
Close button needs to have an `aria-label` set to Close

Also we need to be able to close the modal by pressing enter key. At the moment it's only closing with escape key.

**Comment by samanthaksanders** [comment]
Have fixed close button issue in 1.1.1 release. 

Yet to tick off missing aria label and controls for the close button

**Comment by samanthaksanders** [comment]
Closing this, see #6 for tracking progress on any `aria-label` related fixes
